///
/// @Generated by Mockolo
///



@testable import VBoard


class ViewControllerFactoryMock: ViewControllerFactory {
    init() { }


    var makeAppRootTabBarControllerCallCount = 0
    var makeAppRootTabBarControllerHandler: (() -> (AppRootTabBarControllerProtocol))?
    func makeAppRootTabBarController() -> AppRootTabBarControllerProtocol {
        makeAppRootTabBarControllerCallCount += 1
        if let makeAppRootTabBarControllerHandler = makeAppRootTabBarControllerHandler {
            return makeAppRootTabBarControllerHandler()
        }
        fatalError("makeAppRootTabBarControllerHandler returns can't have a default value thus its handler must be set")
    }

    var makeSearchViewControllerCallCount = 0
    var makeSearchViewControllerHandler: (() -> (SearchViewControllerProtocol))?
    func makeSearchViewController() -> SearchViewControllerProtocol {
        makeSearchViewControllerCallCount += 1
        if let makeSearchViewControllerHandler = makeSearchViewControllerHandler {
            return makeSearchViewControllerHandler()
        }
        fatalError("makeSearchViewControllerHandler returns can't have a default value thus its handler must be set")
    }

    var makeSearchResultViewControllerCallCount = 0
    var makeSearchResultViewControllerHandler: ((String) -> (SearchResultViewControllerProtocol))?
    func makeSearchResultViewController(query: String) -> SearchResultViewControllerProtocol {
        makeSearchResultViewControllerCallCount += 1
        if let makeSearchResultViewControllerHandler = makeSearchResultViewControllerHandler {
            return makeSearchResultViewControllerHandler(query)
        }
        fatalError("makeSearchResultViewControllerHandler returns can't have a default value thus its handler must be set")
    }
}

